- import_playbook: ../init/main.yml

- name: Pre-pull Multus image
  hosts: all
  tasks:
  - name: "Pull nfvpe/multus"
    docker_image:
      name: "nfvpe/multus"


- name: Wait for a ready pod before starting...
  hosts: oo_first_master
  tasks:
    - name: Query for a ready pod...
      oc_obj:
        state: list
        kind: pod
        name: "master-controllers-{{ openshift.node.nodename | lower }}"
        namespace: kube-system
      register: ready_pod
      until:
      - ready_pod.results.results[0].status.conditions | selectattr('type', 'match', '^Ready$') | map(attribute='status') | join | bool == True
      retries: 60
      delay: 5

- name: Multi-network setup
  hosts: all
  gather_facts: false
  tasks:

  - name: Unarchive base CNI plugins tarball
    unarchive:
      src: https://github.com/containernetworking/plugins/releases/download/v0.7.1/cni-plugins-amd64-v0.7.1.tgz
      dest: "/opt/cni/bin/"
      remote_src: yes

- name: Multi-network -- Kubernetes Object setup
  hosts: oo_first_master
  tasks:
  - name: Create temp directory for copying up multinetwork resource files
    command: mktemp -d /tmp/openshift-multinetwork-XXXXXX
    register: mktemp
    changed_when: False

  - name: Copy Multus resource YAML files
    copy:
      src: "files/{{ item }}"
      dest: "{{ mktemp.stdout }}/{{ item }}"
    with_items:
      - multus-daemonset.yml

  - name: Get current
    shell: >
      oc get pods --all-namespaces
    register: all_pods

  - name: Create the Multus daemonset (plus extras from resource definition)
    shell: >
      oc create -f {{ mktemp.stdout }}/multus-daemonset.yml
    when: "'multus' not in all_pods.stdout"
